name: Hotfix deploy
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Provide the recent published ecr version'
        required: true
      deploy-environment:
        type: choice
        description: 'Environment in which the version has to be deployed'
        required: true
        options:
          - uat
          - prod
jobs:

#
# Deploy the build version on ebs
#
  deploy-to-ebs:
    name: "Deploy EB Environment updates and wait for the Environment to become healthy"
    runs-on: ubuntu-latest
    steps:

      - name: Clone orderhub-ci repository
        run: |
          echo "Clone orderhub-ci repo"

      - name: Deploying to EBS
        env:
          PROJECT_VERSION: ${{ github.event.inputs.version }}
          PROJECT_NAME: ecommerce-cart-service
          ENV: ${{ github.event.inputs.deploy-environment }}

        run: |
          echo "ENV :" $ENV
          echo ENVIRONMENT_NAME=`if [[ "$ENV" == "uat" ]]; then echo "$PROJECT_NAME-Uat"; elif [[ "$ENV" == "prod" ]]; then echo "$PROJECT_NAME-Prod-Blue"; fi`
          echo "PROJECT_VERSION :" $PROJECT_VERSION
          echo "Deploying EB Environment updates"
          echo "run update environment script"
          echo "Deployment to EBS done"
